language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh

install:
  - conda create -n testenv pip pytest coverage python=$TRAVIS_PYTHON_VERSION numpy flake8 lmfit pyyaml pandas matplotlib scipy
  - source activate testenv
  # this next line can be removed as soon as conda-forge fixes their pinnings. See https://github.com/conda-forge/staged-recipes/issues/907
  - conda install icu
  - pip install codecov
  - python setup.py install
  - git clean -xfd


script:
  - coverage run run_tests.py
  - coverage report -m

after_success:
  - codecov
