language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels lightsource2
  - conda create -n testenv pip pytest coverage python=$TRAVIS_PYTHON_VERSION numpy flake8 lmfit pyyaml conda-build
  - source activate testenv
  - python setup.py install
  - pip install codecov

script:
  - coverage run run_tests.py
  - coverage report -m
  # add 'exit-zero' so that the my bad code standards dont fail travis
  - flake8 $TRAVIS_BUILD_DIR/ixstools --exit-zero
  - conda build conda-recipe --python=$TRAVIS_PYTHON_VERSION

after_success:
  - codecov